# run `make hello` to see the output 
hello: 
	echo "Hello, world!"
# run `make watch` to watch the file and compile it
watch: 
	sass --watch main.scss ../../za-dark-kai.css
# run `make build` to compile the file
build:	
	sass main.scss ../../za-dark-kai.css